---
- name: mesos slave container
  docker:
    name: slave
    image: redjack/mesos-slave:0.21.0
    env:
      MESOS_MASTER=zk://"{{HOST_IP}}":2181/mesos
      MESOS_EXECUTOR_REGISTRATION_TIMEOUT=5mins
      MESOS_CONTAINERIZERS=docker,mesos
      MESOS_ISOLATOR=cgroups/cpu,cgroups/mem
      MESOS_LOG_DIR=/var/log/mesos
      MESOS_LOGGING_LEVE=INFO
    volumes:
      - /var/run/docker.sock:/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - /sys:/sys:ro
      - mesosslave-stuff:/var/log/
    expose:
      - 5051
    state: running