---
- name: copy Dockerfile
  copy: src=Dockerfile dest=~/Dockerfile force=yes

- name: pull jenkins image
  command: docker pull jenkins:latest

- name: build jenkins custom image
  command: sudo docker build -t cedn/jenkins_with_docker .
  
- name: jenkins container
  docker:
    name: jenkins
    image: cedn/jenkins_with_docker
    ports:
      - "8081:8080"
    volumes:
      - /var/jenkins_home
      - /var/jenkins_data
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
