---
- name: jenkins container
  docker:
    name: jenkins
    image: cedn/jenkins_with_docker
    ports:
      - "8081:8080"
    volumes:
      - /var/jenkins_home
      - /var/jenkins_data
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
